### ISSUE TITLE
Cannot use CurlGridFunctionCoefficient

### ISSUE THREAD

**Issue by aurelio-hm** [mfem/PyMFEM#137]
Hi PyMFEM team,

First of all, thank you for this very nice Python wrapper for the MFEM library. I would like to compute the curl of a vector-valued ParGridFunction, for which I tried to use `CurlGridFunctionCoefficient`. Please see below a very simplified example:
```
import mfem.par as mfem  # mfem.ser produces the same output

gf = mfem.ParGridFunction()  # passing a ParFiniteElementSpace also does not change the output
curl_gf_coeff = mfem.CurlGridFunctionCoefficient(gf)
```
Doing so raises the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/mfem/_ser/coefficient.py", line 608, in __init__
    raise AttributeError("No constructor defined - class is abstract")
AttributeError: No constructor defined - class is abstract
```
Is this supposed to happen? I'm using PyMFEM in an Apple M1 computer. Thanks in advance for your time,

Aurelio

**Comment by sshiraiwa** [comment]
Hi @aurelio-hm.   Can you try using the latest version of of PyMFEM? I think this issue was addressed very recently, when ex31p was created. 
https://github.com/mfem/PyMFEM/commit/9993beadf3b7965bcdc12ba0a7ef164dbad0dc5a

**Comment by sshiraiwa** [comment]
Hi @aurelio-hm. By the way, your traceback says 
```
mfem/_ser/coefficient.py", line 608, in __init__
```
meaning that you are somehow calling serial version. Are you doing import mfem.ser somewhere? Please note that one can either load serial (mfem.ser) or parallel (mfem.par).

**Comment by aurelio-hm** [comment]
Hi @sshiraiwa. I also tried importing `mfem.ser` and setting `gf = mfem.GridFunction()` and accidentally copied its output instead of the one with `mfem.par`.

Indeed, I was using v4.3.0.6. I have compiled the serial wrapper from v4.4.0.0 in macOS and it works perfectly. Many thanks for your help!
