### ISSUE TITLE
FindPointsGSLIB

### ISSUE THREAD

**Issue by adantra** [mfem/PyMFEM#139]
Are there any plans to implement this class in pymfem?

**Comment by sshiraiwa** [comment]
At moment, PyMFEM support FindPointsGLSIB in parallel wrapper. However, our pre-generated wrapper code does not wrap GSLIB. To do this, you need to have SWIG (version 4.0.2) installed and re-generate wrapper. Below are sample steps to do this
starting from vanilla virtualenv.

```
     virtualenv env
     source env/bin/activate
     pip install six mpi4py numba                                 # note (1) Numba is necessary for field_interp.py. 
                                                                                   # note (2) Numba requires slighly old numpy
     cd env;mkdir src;cd src
     git clone git@github.com:mfem/PyMFEM.git
     cd PyMFEM
     python setup.py install --with-gslib --with-parallel  --ext-only     # this build external libraries.
     python setup.py clean --swig                                                      # delete pre-generated wrapper
     python setup.py install --with-gslib --with-parallel  --swig           # re-generate wrapper
     python setup.py install --with-gslib --with-parallel  --skip-ext     # build PyMFEM 
```
Then, you can run find_interp.py in miniapps/gslib
```
      cd miniapps/gslib
      python field_interp.py --visualization
```
If you have glvis installed. Launch it without argument, and it will wait for socket connection. 
The above command will pop-up the following images
![image](https://user-images.githubusercontent.com/1929159/169914289-e48f8a24-e5c5-4c45-9b29-9de321d30e74.png)

**Comment by sshiraiwa** [comment]
Two side notes:
1) GSLIB build script in setup.py somehow did not work without mpi compiler. This needs to be addressed in future
2) Just noticed that the source distribution from PyPI does not contain miniapps sub-directory. Should be fixed later.

**Comment by adantra** [comment]
Thanks! I will try this. It should be straightforward with this information.

**Comment by adantra** [comment]
It worked. Thanks again.
