### ISSUE TITLE
Is it possible to create a mesh object from an array of mesh objects?

### ISSUE THREAD

**Issue by adantra** [mfem/PyMFEM#146]
This constructor exists in c++ ( Mesh::Mesh(Mesh *mesh_array[], int num_pieces) ) and it seems to e available in the python bindings. However I have to been able to make it work.
I have multiple grids obtained from a parallel run and want to build a new grid using a subset of those grids. Any clue?

**Comment by sshiraiwa** [comment]
Thank you for reporting this. It looks like the first input argument (Mesh *mesh_array[]) needs a special handling to make a wrapper clean. Let me look into it bit more how best it can be done

**Comment by sshiraiwa** [comment]
This is going to be added in next (https://github.com/mfem/PyMFEM/tree/next).
In order to make the interface cleaner, MakeMerged (https://github.com/mfem/PyMFEM/blob/next/mfem/_ser/mesh.i#L364) is added.
```
 m1 = mfem.Mesh_MakeCartesian3D(3,3,3,mfem.Element.TETRAHEDRON)
 m2 = mfem.Mesh_MakeCartesian3D(3,3,3,mfem.Element.TETRAHEDRON)
 for i in range(m2.GetNV()):
        vv = m2.GetVertexArray(i)
        vv += 2.5
 m3 = mfem.Mesh_MakeMerged((m1, m2))
  m3.Print('merged_mesh.mesh')
```
![image](https://user-images.githubusercontent.com/1929159/193475460-c776b9a2-62a2-4c9b-bc47-7b80e32c9c81.png)

**Comment by sshiraiwa** [comment]
Side note: starting from the next branch, SWIG is needed in your command search path. If you don't have it 
```
pip install swig
```
will do what you need.
Once, PyMFEM is cloned from repository, for example
```
python setup.py install --with-parallel 
```
will do
1) clone and build METIS (using the one under MFEM repo), and Hypre
2) clone and build MFEM (twice with serial and parallel)
3) generate wrapper codes using SWIG (<- new)
4) build the wrapper code.

Please let me know if you find any issue.

**Comment by adantra** [comment]
@sshiraiwa, thanks! I will try this branch this weekend.

**Comment by adantra** [comment]
Unfortunately I cannot use this branch because an issue with GKlib. I am using intel compilers.

**Comment by sshiraiwa** [comment]
Hi @adantra. Can you upload the error message you are seeing? Next does not depends on GKlib as long as setup.py builds METIS. Are you providing METIS build from somewhere else?

**Comment by adantra** [comment]
@sshiraiwa the whole compilation output is atached:
[pymfem_compile_out.txt](https://github.com/mfem/PyMFEM/files/9737284/pymfem_compile_out.txt)

**Comment by sshiraiwa** [comment]
@adantra 
Thank you. Looks like MFEM build is failing. In the last cmake command, i noticed  -DCMAKE_CXX_COMPILER=mpiicc.
If I am not mistaken, C++ compiler should be icpc and mpiicpc. Are you passing as follows?
-```
-CC=icc --CXX=icpc --MPICC=mpiicc --MPICXX=mpiicpc
```

**Comment by adantra** [comment]
@sshiraiwa, yes. This is the command line I am using
python setup.py install --with-parallel --CC=icc --CXX=icc --MPICC=mpiicc --MPICXX=mpiicc

**Comment by sshiraiwa** [comment]
CXX needs to point c++ compiler. (same as MPICXX). icc is C-compiler and they are not the same.
Please change it to --CXX=icpc and --MPICXX=mpiicpc`

**Comment by adantra** [comment]
I fixed that and the problem persists. I created a fresh environment and tried again. Here is the output:
[output.txt](https://github.com/mfem/PyMFEM/files/9738032/output.txt)

**Comment by sshiraiwa** [comment]
Hi @adantra. This log file looks much shorter and looks like it fails building METIS. 
In line#16, it says "c++ compiler : icc". This should be icpc
Also, line#69 says "Download metis skipped. Use clean --all-exts if needed". So, somehow, METIS was already downloaded.

Can you please try
```
python setup.py clean --all
```
This should clean whatever garbage from previous build failure, So
```
ls external/
```
should be empty. Then, try running the following.
```
python setup.py install --with-parallel --CC=icc --CXX=icpc --MPICC=mpiicc --MPICXX=mpiicpc --verbose
```
Here, -CXX=icpc is to use intel c++ compiler and --verbose will print more diagnostic information for build failure debugging.

**Comment by adantra** [comment]
@sshiraiwa, I tried your suggestions, and now everything works as expected. Thanks!
