### ISSUE TITLE
module 'mfem.par' has no attribute 'QuadratureSpace'

### ISSUE THREAD

**Issue by benzwick** [mfem/PyMFEM#151]
This was working about a year ago, but now `QuadratureSpace` is not available:
```
In [1]: import mfem.par as mfem
   ...: mesh = mfem.Mesh(10, 10, "TRIANGLE")
   ...: qspace = mfem.QuadratureSpace(mesh, 0)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-fee26b20964c> in <module>
      1 import mfem.par as mfem
      2 mesh = mfem.Mesh(10, 10, "TRIANGLE")
----> 3 qspace = mfem.QuadratureSpace(mesh, 0)

AttributeError: module 'mfem.par' has no attribute 'QuadratureSpace'
```

**Comment by sshiraiwa** [comment]
Thanks. This is oversight. It looks like QuadratureSpace was moved to qspace.hpp in recent MFEM, thus using --mfem-branch='master' makes it disappear.

**Comment by sshiraiwa** [comment]
@benzwick I am trying to address this in PR#152. Please let me know if this works for you.

**Comment by benzwick** [comment]
@sshiraiwa Thanks for looking at this. I will have to wait for #150 because I cannot install parallel MFEM with pip right now.

**Comment by sshiraiwa** [comment]
Okay. I throw in a few more *.i files (https://github.com/mfem/PyMFEM/pull/153). If you have a short example for testing methods you need, please contribute.

**Comment by benzwick** [comment]
Thank you @sshiraiwa, with these additional changes my code is working again.
