### ISSUE TITLE
Mesh constructors and Make methods

### ISSUE THREAD

**Issue by najlkin** [mfem/PyMFEM#167]
Is it possible in _PyMFEM_ to use the Make* methods of `Mesh` for construction of a mesh? In newer versions of _MFEM_, it is customary to use the move constructor `Mesh(Mesh&&)` in combination with these methods to create a refined mesh, for example. However, this does not seem to be possible in _PyMFEM_, since the code `Mesh(Mesh.MakeRefined(...))` results in a call of the copy constructor instead of the move constructor. Such a copy is then unusable, because the refinement data are lost. Using the value returned by `Mesh.MakeRefined(...)` is also not an option, because it is destroyed when getting out of the scope and is passed only by value, so all references in finite element spaces or elsewhere become invalid, causing segfaults eventually.

It seems a solution for this is [being brewed in _SWIG_](https://github.com/swig/swig/issues/1044), but it is not automatic at the moment (prior to the version 4.1.1 of _SWIG_), so a workaround is needed. I have tried _SWIG_ 4.1.1 with _MFEM_ 4.5.0.1 from pip and it also does not work out of the box.

**Comment by pazner** [comment]
Does something like this not work?
```py
mesh_refined = mfem.Mesh.MakeRefined(mesh, 3, mfem.BasisType.GaussLobatto)
```

I'm not sure why you would need `Mesh(Mesh.MakeRefined(…))`.

**Comment by najlkin** [comment]
It is the same reason as in C++ code, you need to make a pointer to the object. There used to be special constructors for all these things in _MFEM_, but it has been replaced by the move constructor combined with these Make* functions to make the interface a bit cleaner. The static function `MakeRefined` returns a value (without copying thanks to the move constructor). _SWIG_ then wraps the value and handles it like that, so the mesh is copied (by the copy constructor) whenever you pass it to a function or return it. However, the copy constructor does not preserve all structures like the refinement transformations, for example. Secondly, all internal pointer to the original mesh are invalid and you end up with a segfault when using something derived, e.g. `FiniteElementSpace` etc.

**Comment by sshiraiwa** [comment]
Thank you for suggestion and explanation. The move semantics is rather new to me. 
Related SWIG is probably this one. 
https://www.swig.org/Doc4.1/CPlusPlus11.html#CPlusPlus11_move_only
I need to do an experiment first to better understand how to use it.

**Comment by najlkin** [comment]
So, as I see it, there are these possible solutions:

- make that move constructor working using the features of the new _SWIG_ versions
- add the special constructors to `Mesh` in _PyMFEM_ like it was back in the day in _MFEM_
- change/add the Make* functions to "factories" producing pointers owned by the user, which is not a good practice in C++ maybe, but it is handled safely by _SWIG_.

**Comment by sshiraiwa** [comment]
Hi @najlkin,
Looking into this, I am not sure if I understoodnd your point. 

When SWIG wraps MakeRefined, it does the following 
```
  # calls MFEM routine
  result = mfem::Mesh::MakeRefined(*arg1,arg2,arg3);  

  # then, wraps the return value in order to pass it to Python
  resultobj = SWIG_NewPointerObj((new mfem::Mesh(result)), SWIGTYPE_p_mfem__Mesh, SWIG_POINTER_OWN |  0 ); 
```    
```resultobj``` is a PyObject, which we can see from Python. With SWIG 4.1.1, result is ```SwigValueWrapper```. Therefore ```new mfem::Mesh(result)``` is handled by a move constructor, not a copy constructor.

I tend to think, as @pazner suggests, ```mesh_refined = mfem.Mesh.MakeRefined(mesh, 3, mfem.BasisType.GaussLobatto)``` would be enough, and you don't need to pass it to ```Mesh()```.

Perhaps I am missing something. Please let me know.

**Comment by najlkin** [comment]
Thanks @sshiraiwa , I was not aware of this wrapping code automatically produced by SWIG. It is exactly the third solution I was proposing. This way it certainly works with SWIG 4.1.1. I was a little bit rush when concluded it does not work. I was getting segfaults like before, so I thought it has the same reason, but the culprit was different. Just one of the objects depending on `Mesh`, which I used for accessing it, went out of the scope.

So, everything is clear and if you do not want to make a workaround for the older versions of SWIG (?), I would say we may close this. Thanks :wink: .

**Comment by sshiraiwa** [comment]
Great.  Workaround for an old SWIG could be a log of work ;D  Since swig >= 4.1.1 is in requirements.txt, let's close this.
