### ISSUE TITLE
Inheritance and Dynamic casting in python

### ISSUE THREAD

**Issue by mortezah** [mfem/PyMFEM#17]
@sshiraiwa 

Assuming that I have all the wrappers implemented, what would be the best way to achieve the equivalent of the following C++ code in python:

```
ParMesh *pmesh = new ParPumiMesh(MPI_COMM_WORLD, pumi_mesh); 
ParPumiMesh* pmesh2 = dynamic_cast<ParPumiMesh*>(pmesh); 
```

Here `ParPumiMesh` is a subclass of `ParMesh`.

**Comment by sshiraiwa** [comment]
I encountered a similar situation with mfem::BlockOperator::GetBlock, which returns the baseclass object. My solution was to add Opr2SparseMat and Opr2HypreParMat

I added ParMesh2ParPumiMesh in pumi.i. Please pull the one from pumi_dev sshiraiwa/PyMFEM

**Comment by mortezah** [comment]
@sshiraiwa 

This worked. Thanks.

I am also closing this issue.
