### ISSUE TITLE
Is it possible to link to an existing mfem library? 

### ISSUE THREAD

**Issue by jan-janssen** [mfem/PyMFEM#173]
I found the `mfem` conda package and I was wondering if I can install the `pymfem` package from pip without recompiling the `mfem` library?

**Comment by sshiraiwa** [comment]
Hi @jan-janssen, I didn't use PyMFEM with conda mfem. Is it install a pre-compiled binary or source code?
If so, setup.py takes --mfem-prefix --mfem-source as  parameters. With pip, you  need to use --install-option.
to set each of these parameters. If you want to compile it with MPI, you also give --with-parallel, --hypre-prefix
and --metis-prefix.

**Comment by jan-janssen** [comment]
I am a bit confused, I have the `libmfem.so` installed on my system. I am just looking for the `pip` command to link to this already installed version.

**Comment by sshiraiwa** [comment]
Setup.py in PyMFEM generates a wrapper code from the MFEM source code. MFEM can be compiled with various options. 
Depending the option you use, the wrapper code has to change. Therefore, if you have only libmfem.so, you can not do pip install.

**Comment by jan-janssen** [comment]
It was compiled with:  https://github.com/conda-forge/mfem-feedstock/blob/main/recipe/build.sh
```
make config CXX=$CXX PREFIX=$PREFIX MFEM_SHARED=YES MFEM_STATIC=NO MFEM_USE_MPI=YES MFEM_USE_METIS_5=YES CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" LIBS="$LIBS" HYPRE_OPT="-I$PREFIX/include" GHV_CXX=$CXX_FOR_BUILD
make lib
make install
```

**Comment by sshiraiwa** [comment]
We don't have a plan to change setup.py for this specific installation pattern.  Probably, better approach would be to modify the feedstock and build the wrapper together.

**Comment by jan-janssen** [comment]
> We don't have a plan to change setup.py for this specific installation pattern. 

I can patch the `setup.py` I just do not fully understand which option to change. I tried to add `python -m pip install . -vv --mfem-prefix=${PREFIX}` but that did not work. Can you just tell me how to disable the build process?

**Comment by sshiraiwa** [comment]
In setup.py,  we run SWIG to generate a wrapper code. SWIG needs to read all C++ header files.
The location of header files is set by using --mfem-source option. If Conda package does not contain
header file, SWIG will fail and thus we can not build PyMFEM.
