### ISSUE TITLE
Question: What is the equivalent of C++ arrays in the wrappers

### ISSUE THREAD

**Issue by mortezah** [mfem/PyMFEM#18]
@sshiraiwa 

What would be the best way to achieve the equivalent of the following c++ code using the python wrappers:

```
   int ip_cnt = 0;
   IntegrationRule vert_template(4);
   IntegrationPoint& ip = vert_template.IntPoint(ip_cnt++);
   double pt_crd[3] = {0., 0., 0.};
   ip.Set(pt_crd, 3); 
```

More specifically, the last 2 lines.

**Comment by sshiraiwa** [comment]
This method is not wrapped in a special way. But can you use ip.Set3(0, 0, 0); ?

**Comment by mortezah** [comment]
That worked. Thanks.
