### ISSUE TITLE
segment-nurbs.mesh won't run in PyMFEM

### ISSUE THREAD

**Issue by gillette7** [mfem/PyMFEM#180]
A colleague and I are trying to use to the file `segment-nurbs.mesh` for a project employing PyMFEM but it seems it will not work for some reason.  For instance, regular compiled mfem will handle this mesh:
`$ ./ex1 -m ../data/segment-nurbs.mesh`
runs without error.  But the PyMFEM equivalent:
`$ python ex1.py -m ../data/segment-nurbs.mesh`
produces a segmentation fault, or in some cases this error:
`Mesh::GetElementEdges(...) element to edge table is not generated.
Abort trap: 6`
Some notes:
- Other nurbs meshes work fine with PyMFEM.  
- The file `segment-nurbs.mesh` is part of the mfem repo but not part of the PyMFEM repo (we copied it over)
- It was advised to us that `segment-nurbs.mesh` is problematic for glvis (it cannot load the mesh) if that is relevant.  

Thanks for any advice!

**Comment by sshiraiwa** [comment]
Closing this, since it seems resolved with a newer version.
