### ISSUE TITLE
Typo in coefficient_common.i

### ISSUE THREAD

**Issue by goodman17c** [mfem/PyMFEM#181]
This error occurs in the _ser build of PyMFEM within the coefficient_common.i file
In lines 67 and 69, there is a typo, where agrs is used rather than args resulting in python error when a sumcoefficient is used.

```
%pythonappend SumCoefficient::SumCoefficient %{
    if len(args) > 0 and isinstance(agrs[0], Coefficient):
          self.linkA = args[0]
    if len(args) > 1 and isinstance(agrs[1], Coefficient):
          self.linkB = args[0]
```

**Comment by goodman17c** [comment]
#182 I submitted a PR to resolve this bug.

**Comment by sshiraiwa** [comment]
Thank you so much!
