### ISSUE TITLE
`FindPointsGSLIB::GetCode()` does not return `mfem::Array<unsigned int>`

### ISSUE THREAD

**Issue by dreamer2368** [mfem/PyMFEM#193]
Hello,

I'm trying to use `FindPointsGSLIB` class within PyMFEM. One function I need to use is `FindPointsGSLIB::GetCode()`, which returns `mfem::Array<unsigned int>` according to the [definition](https://docs.mfem.org/html/classmfem_1_1FindPointsGSLIB.html#ae689e403958c44bd44aaadd9177989e7).

In PyMFEM, this function only returns a `SwigPyObject` that is not associated with any mfem class. For example, I added three lines of code on line 199 of `miniapps/gslib/field_interp.py`:
```
# Evaluate source grid function
interp_vals = mfem.Vector(nodes_cnt * tar_ncomp)
finder = mfem.FindPointsGSLIB()
finder.Setup(mesh_1)
finder.Interpolate(vxyz, func_source, interp_vals)

# Added lines
code_out = self.finder.GetCode()
print(type(code_out))
print(code_out.__dir__())
```

The resulting output is:
```
<class 'SwigPyObject'>
['__repr__', '__getattribute__', '__lt__', '__le__', '__eq__', '__ne__', '__gt__', '__ge__', '__int__', 'disown', 'acquire', 'own', 'append', 'next', '__doc__', '__hash__', '__new__', '__str__', '__setattr__', '__delattr__', '__init__', '__reduce_ex__', '__reduce__', '__subclasshook__', '__init_subclass__', '__format__', '__sizeof__', '__dir__', '__class__']
```

The output object does not have any attribute related to `mfem::Array<unsigned int>`. What is the proper way to use the function `FindPointsGSLIB::GetCode()`?

**Comment by sshiraiwa** [comment]
Thank you. I am aware of this error since I had the same before in https://github.com/mfem/PyMFEM/actions/runs/5290338765/job/14322386378.
My understanding is that this need to be fixed on C++ side.

**Comment by sshiraiwa** [comment]
Thank you for reporting this. It tooked (very) long to address this. This is is going to be resolved in PyMFEM4.6 (https://github.com/mfem/PyMFEM/pull/204).
```
       - wrappers for Array<char>, Array<long long>, and Array<unsigned char> are added as
         uintArray, int8Array, int64Array.
       - Since Array<unsigned int> is not explicitly instantiated in Array.cpp, thus some
         method such as Print, Sort etc are not avaialbe. As a workaround, GetDataArray is
         added to return a numpy array view of underlying memory section.
             >>> v = mfem.uintArray(10)
             >>> v.GetDataArray()[:] = (1, 105, 20, 3, 50, 4, 2, 15, 8)
             >>> v.GetDataArray()[:] = np.sort(a.GetDataArray())
             >>> v.ToList()
              [1, 2, 3, 4, 8, 15, 20, 50, 105, 300]
```
