### ISSUE TITLE
How to implement LinearFormIntegrator

### ISSUE THREAD

**Issue by lys-devel** [mfem/PyMFEM#196]
Hello, I am very new in PyMFEM and I'm trying to implement an original LinearFormIntegrator, but it failed.
The code below is minimal example to reproduce the problem.
(I use Python3.9.1 and mfem 4.5.2.1.)
```
import mfem.ser as mfem

class TestIntegrator(mfem.LinearFormIntegrator):
    def __init__(self):
        super().__init__() # Line 7

    def AssembleRHSElementVect(self, el, Tr, elvect):
        pass

mesh = mfem.Mesh("beam-tri.mesh", 1, 1)
dim = mesh.Dimension()
fec = mfem.H1_FECollection(2, dim)
fespace = mfem.FiniteElementSpace(mesh, fec, dim)

s = TestIntegrator()
b = mfem.LinearForm(fespace)
b.AddDomainIntegrator(s)
```

When I initialize TestIntegrator, the error below is raised.
```
Traceback (most recent call last):
  File "-/test2.py", line 18, in <module>
    s = TestIntegrator()
  File "-/test2.py", line 6, in __init__
    super().__init__()
  File "-/python3.9/site-packages/mfem/_ser/lininteg.py", line 113, in __init__
    raise AttributeError("No constructor defined - class is abstract")
AttributeError: No constructor defined - class is abstract
```
Then I tried to replace "super().__init__()" in line 7 with "pass" to omit calling constructor of TestIntegrator, and got the error below.

```
Traceback (most recent call last):
  File "-/test2.py", line 20, in <module>
    b.AddDomainIntegrator(s)
  File "-/python3.9/site-packages/mfem/_ser/linearform.py", line 150, in AddDomainIntegrator
    lfi.thisown=0
  File "-/python3.9/site-packages/mfem/_ser/lininteg.py", line 110, in <lambda>
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
AttributeError: 'TestIntegrator' object has no attribute 'this'
```
Could you please let me know hot to implement it properly?
I think I can implement AssembleRHSElementVect by myself because I can implement BilinearFormIntegrator follwing ex18.

**Comment by sshiraiwa** [comment]
This was not possible until 4.6.1 without modifying SWIG files. Version 4.6.1 added sub-classing these form integrators in Python. For expanding ```LnearFormIntegrato```, one can subclass ```PyLinearFormIntegrator```. Please take look at examples/ex38.py
