### ISSUE TITLE
Modify an existing mfem.Mesh

### ISSUE THREAD

**Issue by mshaocong** [mfem/PyMFEM#212]
Hello! I am considering if there any way to modify the vertices of `mfem.Mesh`. I am testing some ideas in optimizing the mesh using gradient descent. I would like to do something like the following: 

```
import mfem.ser as mfem

mesh = mfem.Mesh(10, 10, "TRIANGLE")
node = mesh.GetVertex(0) # get the first node 

# edit the first node like this:
node = node + 0.01
``` 

Can I ask if this function is supported by PyMFEM? How can I update the mesh? 

Really appreciate your help.

**Comment by sshiraiwa** [comment]
How about this?
```
mesh = mfem.Mesh(10, 10, "TRIANGLE")
for x in mesh.GetVertexArray():
    x[:] = (x[0]*2, x[1]*3)
mesh.Save("streched.mesh")
```
mesh.GetVertexArray returns tuple of numpy array, each of which points to a mesh vertex data. You can use in-place replacement numpy array to modify the mesh. 
(Thinking about this, it might have been better to return Python iterator)

**Comment by mshaocong** [comment]
> How about this?
> 
> ```
> mesh = mfem.Mesh(10, 10, "TRIANGLE")
> for x in mesh.GetVertexArray():
>     x[:] = (x[0]*2, x[1]*3)
> mesh.Save("streched.mesh")
> ```
> 
> mesh.GetVertexArray returns tuple of numpy array, each of which points to a mesh vertex data. You can use in-place replacement numpy array to modify the mesh. (Thinking about this, it might have been better to return Python iterator)

Thank you so much! It is exactly what I expect.
