### ISSUE TITLE
cxx11flag in mfem/_ser/setup.py

### ISSUE THREAD

**Issue by rw-anderson** [mfem/PyMFEM#22]
In the line:  

extra_compile_args = [cxx11flag, '-DSWIG_TYPE_TABLE=PyMFEM']

where is cxx11flag supposed to come from?  It errors out as an undefined name for me when I invoke make ser.

**Comment by sshiraiwa** [comment]
This is a flag to turn on C11 feature in compiler. Can you export it before
running make 

export CXX11FLAG=-std=c++11
make ser

**Comment by rw-anderson** [comment]
Ok, thanks, that seemed to work.  I don't think that's mentioned in the INSTALL instructions, and it fails if it isn't set.

**Comment by sshiraiwa** [comment]
Thank you for verifying it. INSTALL instruction will be updated in the next pull request to address the issue #23
