### ISSUE TITLE
PyMFEM 4.7

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/PyMFEM#223]
MFEM 4.7 is released. (Congratulation to the team). This is ToDo list for PyMFEM 4.7
- [x] https://github.com/mfem/PyMFEM/pull/219
- [x] Update github actions to test
- [x] ex39.py (https://github.com/mfem/PyMFEM/compare/mfem_47_dev...fix-example-23-39p?expand=1)
- [x] update ex18.py (https://github.com/mfem/PyMFEM/issues/227, https://github.com/mfem/PyMFEM/pull/235)
- [x] address ex23.py
- [x] update SWIG requirement to >= 4.2.1 (https://github.com/mfem/PyMFEM/pull/226)
- [x] Improve testing workflow (https://github.com/mfem/PyMFEM/pull/222)
- [x] https://github.com/mfem/PyMFEM/pull/225
Carried over from 4.6
- [x] Include test with Python3.11
- [x]  update libceed version to 0.12 (used when --with-libceed is on) (https://github.com/mfem/PyMFEM/pull/240)
- [x] Fix CUDA test in github action (https://github.com/mfem/PyMFEM/pull/241)
- [x] Update Install.md and ChangeLog (https://github.com/mfem/PyMFEM/pull/246, https://github.com/mfem/PyMFEM/pull/244)

**Comment by joetristano** [comment]
Will master pymfem build against 4.7 mfem? Not looking to take advantage of the functionality yet, just want to keep a single binary executable stream.

**Comment by jtristano** [comment]
Any updates on this?

**Comment by sshiraiwa** [comment]
@jtristano. Looking at this test (https://github.com/mfem/PyMFEM/actions/runs/9725566030/job/26843041174), the current master can be built with the current MFEM master. New 4.7 functionality is not yet supported, however.

**Comment by jtristano** [comment]
Thank you!

**Comment by sshiraiwa** [comment]
Closing this. Moving to the next one (https://github.com/mfem/PyMFEM/issues/242)
