### ISSUE TITLE
segfault in ncmesh interface

### ISSUE THREAD

**Issue by rw-anderson** [mfem/PyMFEM#23]
The minimal C++ test program to call the method GetElementDepth() on ncmesh:

```
#include "mfem.hpp"
using namespace mfem;

int main()
{
   Mesh *mesh = new Mesh("./mfem/data/star.mesh", 1, 1);
   mesh->EnsureNCMesh();

   int depth = mesh->ncmesh->GetElementDepth(0);
   printf("depth = %d\n",depth);
}
```
produces the expected output of "depth = 0" with a clean exit.

But what I think is the equivalent program in PyMFEM:

```
import mfem.ser as mfem

mesh = mfem.Mesh("./mfem/data/star.mesh",1,1)
mesh.EnsureNCMesh()

depth = mesh.ncmesh.GetElementDepth(0)
print("depth = %d" % depth)
```

results in a segfault at the call to GetElementDepth.

Any thoughts on this?

**Comment by sshiraiwa** [comment]
Thank you for reporting this. I was able to reproduce it. I don't see
obvious reason to do seg-fault, but I am guessing this is some memory handling 
issue? Looking into it.

**Comment by sshiraiwa** [comment]
It turned out that this is caused may missing 
   import_array();
in ncmesh.i (SWIG recipe file). I am going to check if there is similar error in other *.I file, and make a fix.
