### ISSUE TITLE
How to Install PyMFEM so that it reads Cubit Files?

### ISSUE THREAD

**Issue by silverrose-llnl** [mfem/PyMFEM#232]
Hello!

I'm trying to read cubit files and I am getting the following error:

```
RuntimeError: PyMFEM error (mfem::ErrorException): MFEM abort: NetCDF support requires configuration with MFEM_USE_NETCDF=YES
 ... in function: void mfem::Mesh::Loader(std::istream&, int, std::string)
 ... in file: /__w/PyMFEM/PyMFEM/PyMFEM/external/mfem/mesh/mesh.cpp:4143
```

I installed PyMFEM using pip install. Is there a way to reinstall it so that it reads cubit files? Do I need to download the repo, change an option in the .cpp file and reinstall from there?

Thanks in advance!

**Comment by justinlaughlin** [comment]
Hi - some of the dependency builds options are exposed as flags in the PyMFEM build but not all. I think the easiest option may be to install MFEM with what you need (e.g. using the `MFEM_USE_NETCDF` flag) and then pointing to it when you install PyMFEM. [Here is some code](https://github.com/mfem/PyMFEM/issues/205#issuecomment-1913829789) that installs using an external MFEM.
