### ISSUE TITLE
Mesh Atributtes and .vtk/.vtu files

### ISSUE THREAD

**Issue by silverrose-llnl** [mfem/PyMFEM#233]
Hello!

I'm trying to read the following .vtk/,vtu mesh that has 3 material regions:

![image](https://github.com/mfem/PyMFEM/assets/175169798/b83fa81e-4272-4313-8c35-877e6b19a498)

I added both a cell data array "material" and an "attribute " based on the [MFEM website](https://mfem.org/mesh-formats/#vtk-mesh-formats). But when I read the mesh into MFEM, all the attributes are set to 1. Is there another keyword I should be adding? Is there something wrong with the format of the .vtk/.vtu files (attached here - [sample_1_mesh_pave.zip](https://github.com/user-attachments/files/16169852/sample_1_mesh_pave.zip))?

![image](https://github.com/mfem/PyMFEM/assets/175169798/9fec6dbc-aeca-41aa-b3a5-3cc5cc549d37)

On a tangential topic. Since I have a list of the attributes I want readily available, I thought that I could do it with `mesh.SetAttribute(1,<att_list>)` but it seems that it only accepts integers and not lists. I'm new to using MFEM, so I'm still trying to grasp the syntax.  Is there a way to add attributes to each element of an existing mesh?  (EDIT: Actually figured out out to do this with LivChat)

Thanks in advance!
Isa

**Comment by v-dobrev** [comment]
Try the format used here: https://github.com/mfem/mfem/blob/988439f60a9902e29572b83dcb2a142eb8da3dbd/data/beam-hex.vtk#L60-L70
