### ISSUE TITLE
Is there a faster way to do find points with PyMFEM ?

### ISSUE THREAD

**Issue by jtristano** [mfem/PyMFEM#251]
Hi,
I have a cartesian mesh where I can integerize the lookup of elements.  I want to paralleize the getting the integration points for a set of points in space given the associated element to the point that I can find quickly,  how would I parallelize the calculation of the integration points with pymfem so that I dont have to call mesh.FindPoints which is inefficient?

Can I then , in parallel sample a grid function with these points?

All of this in python?

I'm open to using numba and whatever other python tricks we can use.

Thanks
Joe

**Comment by jtristano** [comment]
found a way ...

**Comment by tzanio** [comment]
do you mind posting the solution?
