### ISSUE TITLE
How to wrap real_t & variables?

### ISSUE THREAD

**Issue by silverrose-llnl** [mfem/PyMFEM#257]
Hello!

I'm trying to wrap TMOP functions to work with pymfem. I'm having trouble with dealing with  some of the metrics that use inputs of the type "real_t &" (Like in TMOP_Metric_313 ). This is my first time wrapping anything, hence I tried to do it in the following way but it didn't work in  tmop.i :

```
%typemap(in) (mfem::real_t &mindet) (PyArrayObject &tmp_arr1_ = NULL){
    tmp_arr1_ = (PyArrayObject &)(PyList_GetItem($input,0))
    $1 = (double &) PyArray_DATA(tmp_arr1_);
    PyArray_CLEARFLAGS(tmp_arr1_, NPY_ARRAY_OWNDATA);
}
%typemap(freearg) (mfem::real_t &mindet){
}
%typemap(typecheck ) (mfem::real_t &mindet){
  /* check if list of 5 numpy array or not */
  if (!PyList_Check($input)) $1 = 0;
  else {
     if (PyList_Size($input) == 1){
       $1 = 1;
       if (!PyArray_Check(PyList_GetItem($input,0))) $1 = 0;
     } else $1 = 0;
  }
}
```

But that didn't work. How can I wrap 'realt &' and 'realt *' input variables properly? 

Thanks in advance!

**Comment by sshiraiwa** [comment]
Hi @silverrose-llnl, this solution may look bit hacky, but you can actually create a pointer to real_t using 
Vector::GetData(), like this. 
```
Python 3.11.7 (main, Jan  1 2024, 01:29:44) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mfem.ser as mfem
>>> vec = mfem.Vector([1.])
>>> vec.GetData()
<Swig Object of type 'double *' at 0x105074480>
>>> mfem.tmop.TMOP_Metric_313(vec.GetData())
<mfem._ser.tmop.TMOP_Metric_313; proxy of <Swig Object of type 'mfem::TMOP_Metric_313 *' at 0x1050ffcc0> >
```
Side note:
 Wrapper for classes defined in tmop.hpp, tmop_tools, and tmop_amr are under mfem.tmop.*.
 real_t is defined in config/config.hpp. This is wrapped in common/mfem_config.i and imported at the beginning of tmop.i 

Hope this works for you.
