### ISSUE TITLE
Read mesh from GMSH into PyMFEM

### ISSUE THREAD

**Issue by Pratikk17** [mfem/PyMFEM#28]
Dear Sir,

I have a mesh generated using GMSH (in .msh) format. I can view it using glvis. But I do not understand how to import it into MFEM. What changes need to be done in the statement
"mesh=mfem.Mesh(meshfile,1,1) ?
Sorry for basic question.
Thank you very much.
Best,
Pratik

**Comment by v-dobrev** [comment]
Just for reference: this question was answered here: https://github.com/mfem/mfem/issues/1438

**Comment by sshiraiwa** [comment]
mesh=mfem.Mesh(meshfile,1,1)
