### ISSUE TITLE
SaveVTK and PrintVTK wrappers

### ISSUE THREAD

**Issue by mortezah** [mfem/PyMFEM#29]
Are wrappers for `Mesh::void PrintVTK(std::ostream &out, int ref, int field_data=0);` and  `GridFunction::SaveVTK(std::ostream &out, const std::string &field_name, int ref); `, implemented in PyMFEM? If yes, how should one create a `std::ostream` object in python and pass it to the corresponding wrapper?

**Comment by sshiraiwa** [comment]
This is very late response (sorry)
We wrap std::ostream using https://github.com/mfem/PyMFEM/blob/master/mfem/common/io_stream_typemap.i
For a user perspective, passing a file name instead of the ostreme object will do the trick.

**Comment by mortezah** [comment]
No worries. I figured that out shortly after posting the issue. I should have removed the issue but I forget.
