### ISSUE TITLE
how does "pip install mfem" should work????

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/PyMFEM#36]
Since PyMFEM 4.2 passed my test, I started looking into the idea of making mfem + wrapper install-able from pip.

And I would like to have your input in terms of how/what PIP installer should do.
My current thought is following. 

For the wrapper to work, at the very minimum, the following three should happen
1) Install a specific version of mfem
2) built it as a dynamic library
3) build the wrapper code and install it. 

It looks doable to write setup.py to do all of them, and because the wrapper requires a 
specific version of mfem, probably it makes sense to do this all together, instead of asking 
a user to install mfem separately and specify the library path.

My question is about how we should be handling dependency libraries. 

I could support very basic things such as METIS and Hypre, since I have a mechanism to install
them (https://github.com/piScope/TwoPi). However, considering ever growing number of dependency and 
the fact that several package tools are available, I am inclined to leave a user to install them
separately. This would keep the setup script reasonably compact, and maintainable.

Please let  me know what you think about this plan. Any suggestion/question (or even throwing 
wrench into this ;D) s welcome.

**Comment by jcwright77** [comment]
Just my two cents:
pip is for installing python modules and their python dependencies. It does
not install underlying system libraries. For example pip install mysql does
not install mysql itself only the python wrappers.

I would suggest relying on other existing ways of installing mfem itself such
as spack or the existing make/cmake in the distribution. If you want a full
stack package manager for python modules and library dependencies, anaconda
tries to do that. Users will in general not expect pip to be installing the
mfem library and solvers.

Another complementary route would be to add a make/cmake target to the mfem
distribution itself that can install pymfem.

-john

**Comment by sshiraiwa** [comment]
@jcwright77 Thank for supporting the plan. Yes, CMAKE in MFEM distribution will be used to install 
mfem. 

From user's perspective, however, installing the wrapper without installing mfem ready to use doesn't 
make much sense. The idea, here, is to minimize what a new user needs to do. For example, when 
he/she installs ubuntu to a new PC box, and wants to try mfem with Python w/o before doing anything 
else ;D   

I thought about the second approach too, but it requires the wrapper to be ready when MFEM 
releases C++, which is unlikely at this point. But there may be a good way to take this route.
@tzanio, what do you think?

By the way, "pip install wxpython" installs wxwidgets, "pip install gmsh" install  gmsh itself, and there is 
even "pip installl cmake".

**Comment by jcwright77** [comment]
Ok I stand corrected. A single install command will be useful. I guess pip packages are a little inconsistent on what they do. 

-john

**Comment by v-dobrev** [comment]
I think it makes sense for `pip install mfem` to install the minimal parallel version of MFEM -- this requires c++ compiler, MPI, METIS and HYPRE. If users want to enable more external libraries in MFEM, things will be tricky. They can build the extended version of MFEM themselves and point PyMFEM to that build with an environment variable. However, I don't know if PyMFEM can update itself and create additional wrappers for the new classes and functions provided by MFEM for the additional external libraries. Maybe these can be separate packages, e.g. one will need to install `pip install mfem-petsc`.

**Comment by sshiraiwa** [comment]
@v-dobrev Thank you for your input. I think we will add mpi4py as a dependency when installing the parallel version.
We can then ask mpi4py what mpi compiler is used. Installing METIS and HYPRE from setup.py is certainly possible.

Regarding other dependencies, ]I think we can write setup.py to run SWIG to generate a wrapper code when extra flat
like --with-mumps is on. Then, in the script to generate wrapper code (SWIG interface file, or so-called i-file), we can load config.hpp and use #ifdef-#endif.
In fact, PUMI extension is already using this feature. We can do the same for other libraries.

**Comment by v-dobrev** [comment]
So if you first install `pip install mfem` and later decide to build your own MFEM version with more external libraries, then you just need to re-install the `mfem` python package (pointing it to the new MFEM build with an environment variable). Is that what you're thinking?

**Comment by sshiraiwa** [comment]
@v-dobrev. Yes. Just to be clear, I am thinking to create the following command like options.

python setup.py                          # install mfem and PyMFEM in serial
python setup.py --with-parallel    # install mfem/metis/hypre and PyMFEM in both serial and parallel (require mpi4py)
python setup.py --mfem-prefix = <somewhere>   # use <somewhere>/include/mfem/config/config.hpp and other headers
                                                                                link with  <somewhere>/lib/libmfem.so 

Of course, the third option assumes all the libraries are installed as .so so that Python can load it.
Also, in the future, adding a .so checker by calling cmake from setup.py wouldn't be too complicated especially 
there are CMAKE FindXXXs in https://github.com/mfem/mfem/tree/master/config/cmake/modules.

**Comment by sshiraiwa** [comment]
Thank you for your inputs.  I am putting together a new setup script, and I am testing it on TestPyPI. 

https://test.pypi.org/project/mfem/

This is not the official PyPI. It is a site meant for testing a PyPI package. 
I am still testing this. I am going to do at least following test before putting it to PyPI

- [ ]  build on MacOS
- [ ]  check parallel build
- [ ]  add --cuda option  (I need this for myself ;D)

I also cleaned up README.md so that it looks nicer on PyPI and GitHub. Please give me your 
feedback. This work in a brach (https://github.com/mfem/PyMFEM/tree/pip_install_dev)

Note version number is screwed because PyPI does not allow to overwrite he package which was
already uploaded. It will be changed to 4.2.0rc1 when this is uploaded to PyPI.

**Comment by sshiraiwa** [comment]
Closing this issue with this ScreenShot ;D
Additionally, this repo is now configured to test  a release is using Github action.
![Screenshot from 2020-12-08 16-48-32](https://user-images.githubusercontent.com/1929159/101545471-4c5c3400-3975-11eb-9442-a70bd9bfc74c.png)

**Comment by v-dobrev** [comment]
For completeness, the link to the PyPI page is: https://pypi.org/project/mfem.
