### ISSUE TITLE
Consider including Jupyter examples

### ISSUE THREAD

**Issue by tzanio** [mfem/PyMFEM#49]
Consider including [Jupyter](https://jupyter.org/) versions of the examples. See e.g. ex1 and ex9 in https://github.com/GLVis/pyglvis/tree/master/examples.

Ideally hosted also on [Binder](https://mybinder.org/).

**Comment by sshiraiwa** [comment]
Thanks. Base on the off-line discussion, a new Action to create binary release (https://github.com/mfem/PyMFEM/pull/51) is created. (In my understanding, this allows for simplifying a notebook on Binder.). The rest should be straightforward (perhaps), but I will continue to look into it. A pull request for this (and for other things) is always welcome ;D.
