### ISSUE TITLE
Assign spatially varying matrix coefficient

### ISSUE THREAD

**Issue by kaigaox** [mfem/PyMFEM#57]
Hi,

Is there an example on how to assign matrix coefficient to each of the elements in the mesh?

**Comment by sshiraiwa** [comment]
May I ask how your coefficient is defined? If it is a regular function of position, x, y, z, then
one can use MatrixFunctionCoefficient. This can be done in a similar way as VectorPyCoefficient shown in this example https://github.com/mfem/PyMFEM/blob/master/examples/ex3.py#L25. If you are looking for a way to define it differently for example by using finite element index, we need to write it using more low-level MFEM API. It is probably doable, but more involved.

**Comment by kaigaox** [comment]
> May I ask how your coefficient is defined? If it is a regular function of position, x, y, z, then
> one can use MatrixFunctionCoefficient. This can be done in a similar way as VectorPyCoefficient shown in this example https://github.com/mfem/PyMFEM/blob/master/examples/ex3.py#L25. If you are looking for a way to define it differently for example by using finite element index, we need to write it using more low-level MFEM API. It is probably doable, but more involved.

Thanks for the instruction. My coefficients are defined in a n1xn2xn3 discreate grid points in space (regularly sampled, loaded from external file), not an analytical function, and the coefficient is a 3x3 matrix at each grid point. I didn't figure out how to define such a coefficient and apply it to the Poisson during pymfem. What the appropriate mfem API for this and does pymfem include an example of this kind? Thank you very much!

**Comment by sshiraiwa** [comment]
My apology for slow response. 

Assuming it is okay to interpolate each of 3x3 matrix element separately, one way is 
to use RegularGridInterpolator. For example, you can generate an interpolation function in a global scope, like
```
from scipy.interpolate import RegularGridInterpolator as RGI
func = RGI((x, y, z), data)
```
I added a sample matrix_coefficient.
https://github.com/mfem/PyMFEM/blob/master/examples/wrapper_example/matrix_coefficient.py

Although the example returns a fixed 2x2 matrix (it is a 2D example), one can call the above function from inside MatrixPyCoefficient::EvalValue

**Comment by sshiraiwa** [comment]
Closing for now. Feel free to open if you have further questions.
