### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by gillette7** [mfem/PyMFEM#58]
Hi - I'm trying to use pymfem on the supercomputer clusters at LLNL.  I'm using a virtual environment and had no issue with the command `pip install mfem.`  But then, it seems it's not working as a python package:
```
(merlin) [gillette@syrah256:delSp-dev]$ pip list | grep mfem
mfem               4.2.0.8
(merlin) [gillette@syrah256:delSp-dev]$ python -q
>>> import mfem
>>> mesh = mfem.Mesh(10, 10, "TRIANGLE")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mfem' has no attribute 'Mesh'
>>> 
```
I also tried this:
```
(merlin) [gillette@syrah256:delSp-dev]$ python -q
>>> import mfem.ser as mfem
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/g/g12/gillette/projects/intro2merlin/merlin_venv/lib/python3.7/site-packages/mfem/ser.py", line 1, in <module>
    from  mfem._ser.globals import *
  File "/g/g12/gillette/projects/intro2merlin/merlin_venv/lib/python3.7/site-packages/mfem/_ser/globals.py", line 13, in <module>
    from . import _globals
ImportError: numpy.core.multiarray failed to import

```
I feel like I'm missing something basic... any suggestions?  Thanks!

**Comment by sshiraiwa** [comment]
For the first one, loading PyMFEM at the beginning is either

import mfem.ser as mfem
or
import mfem.par as mfem (if you build parallel version)

The second pattern is new to me. In the error message, it says

ImportError: numpy.core.multiarray failed to import,

which sounds like some error in linking numpy??? I suppose you have .so file in the
/g/g12/gillette/projects/intro2merlin/merlin_venv/lib/python3.7/site-packages/mfem/_ser

Can you check them with ldd?  For example, 

ldd /g/g12/gillette/projects/intro2merlin/merlin_venv/lib/python3.7/site-packages/mfem/_ser/_globals*.so

Best,
—
S

**Comment by gillette7** [comment]
Here's what I get:

```
(merlin) [gillette@syrah144:mfem]$ ldd /g/g12/gillette/projects/intro2merlin/merlin_venv/lib/python3.7/site-packages/mfem/_ser/_globals*.so
	linux-vdso.so.1 =>  (0x00002aaaaaacd000)
	libmfem-b2e0d557.so.4.2.0 => /g/g12/gillette/projects/intro2merlin/merlin_venv/lib/python3.7/site-packages/mfem/_ser/../../mfem.libs/libmfem-b2e0d557.so.4.2.0 (0x00002aaaaaede000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00002aaaab86b000)
	libm.so.6 => /lib64/libm.so.6 (0x00002aaaabb73000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002aaaabe75000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaac08b000)
	libc.so.6 => /lib64/libc.so.6 (0x00002aaaac2a7000)
	librt.so.1 => /lib64/librt.so.1 (0x00002aaaac675000)
	/lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)
```
I have a regular, compiled build of mfem in `/usr/workspace/gillette/software/repos/mfem` - not sure if this matters at all.  Thanks for your help!
-- Andrew

**Comment by gillette7** [comment]
Ah - I think I just fixed this with
`pip install -U numpy`
I'll close this issue for now - will re-open if something else comes up.

**Comment by sshiraiwa** [comment]
Okay. Great. I suppose we should put numpy as a dependency….

**Comment by gillette7** [comment]
Maybe it's a version issue?  It was strange because I already had `numpy` installed (version 1.18.3) but it needed 1.20.1 to work.  Anyways, resolved now!
