### ISSUE TITLE
Assigning a constant to ParGridFunction objects

### ISSUE THREAD

**Issue by mortezah** [mfem/PyMFEM#65]
How can the following C++ assignment operator be used in python version of the code

```
ParGridFunction& mfem::ParGridFunction::operator=(double value)
```

having a `ParGridFunction` object `gf` in python and the following expression

```
gf = 0
```

cause the type of `gf` to change.

@sshiraiwa

**Comment by sshiraiwa** [comment]
Hi @mortezah 
You can do gf.Assign(0.0) to set all values of Vector. 
https://github.com/mfem/PyMFEM/blob/master/docs/manual.txt#L124
