### ISSUE TITLE
Not able to build PyMFEM parallel when using swig 4.0.0

### ISSUE THREAD

**Issue by mortezah** [mfem/PyMFEM#66]
@sshiraiwa 

I am not able to compile the parallel version of PyMFEM when locally building the wrappers using swig version 4.0.0. (see the attached log). Is there a minimum version requirement for swig?

[error.log](https://github.com/mfem/PyMFEM/files/6288027/error.log)

I am also attaching the offending wrapper file (compiled with swig version 4.0.0)
[datacollection_wrap_cxx_swig_4.0.0.txt](https://github.com/mfem/PyMFEM/files/6288048/datacollection_wrap_cxx_swig_4.0.0.txt)

**Comment by sshiraiwa** [comment]
Looking into this, the process to import cpointers.i (SWIG library) does not seem quite correct.
I am attempting to fix it in cpointer_fix. Can you take a look at https://github.com/mfem/PyMFEM/pull/70?

**Comment by mortezah** [comment]
@sshiraiwa with the changes in #70 I can not build both serial and parallel versions of PyMFEM successfully.
