### ISSUE TITLE
Output vtk with solution data (how to call PrintVTK or PrintVTU?)

### ISSUE THREAD

**Issue by startrekman** [mfem/PyMFEM#71]
So I can get a working output vtk file by doing the following:

mesh.PrintVTK("outmesh.vtk") 

But I am not sure how to get it to print out the solution. So if I were to have the solution in sol and verts - just like in the example- how would I format mesh.PrintVTK or PrintVTU to show the solution in a field- say in ParaView?

Thank you for your time and help.

**Comment by sshiraiwa** [comment]
I think gf.SaveVTK is the one which is supposed to be used for it. But, it looks like
it is not yet properly wrapped. Let me look into it more...
