### ISSUE TITLE
How to load compressed Mesh or GridFunction from file?

### ISSUE THREAD

**Issue by benzwick** [mfem/PyMFEM#74]
Is there a way to load a grid function from a file using PyMFEM similar to this in MFEM: https://github.com/mfem/mfem/issues/1767

I have tried the following:
```
gf = mfem.GridFunction(filename)
```
and
```
with open(filename) as f:
    gf.Load(f, gf.Size())
```
but neither approach works.

**Comment by sshiraiwa** [comment]
Thanks. Can you use mfem.GridFunction(mesh file,  filename)?
Meantime, I will look into the way you pointed out.

**Comment by benzwick** [comment]
Thanks for the quick reply @sshiraiwa. I did try `mfem.GridFunction(meshfile,  filename)` as well which also didn't work. Now I realized the problem is that I had saved the mesh and grid function as compressed (gz) files (these can be loaded in MFEM C++). I uncompressed the files and I can load them now in PyMFEM using the method you suggested. Is it possible to load the compressed files in PyMFEM as well? In C++ I do it like this:
```
mfem::ifgzstream ifs(filename);
mfem::GridFunction gf(mesh, ifs);
```
which is similar to how it is done in GLVis: https://github.com/GLVis/glvis/blob/95aecd8cf3e3038a36366cef14d5d2986a6a8c1a/glvis.cpp#L1942

**Comment by sshiraiwa** [comment]
Thank you for exploring what is going on. I didn't pay attention the compressed file. I think we can change
a wrapper to check if the filename given by a user ends with ".gz".

**Comment by benzwick** [comment]
I think that would be the best approach. In the meantime do you know if it's possible to create a similar stream in Python as in C++ to uncompress the file and load the data into PyMFEM?

Also, is it possible to save functions to a ParaViewDataCollection? I couldn't find any examples of how to do this.

**Comment by benzwick** [comment]
It would also be nice to be able to read compressed MFEM meshes. This is the error I get when trying to load e.g. `mesh.mesh.gz` (it works fine if I uncompress it first and load that instead):
```
MFEM abort: Unknown input mesh format: �
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-67cc29cfd1a1> in <module>
----> 1 mesh = mfem.Mesh(mesh_ifile)

~/.local/lib/python3.8/site-packages/mfem/_ser/mesh.py in __init__(self, *args)
   1151         __init__(Mesh self, int nx, int ny, char const * type, bool generate_edges=False, double sx=1.0, double sy=1.0, bool sfc_ordering=True) -> Mesh
   1152         """
-> 1153         _mesh.Mesh_swiginit(self, _mesh.new_Mesh(*args))
   1154 
   1155     def PrintToFile(self, mesh_file, precision):

RuntimeError:
```

**Comment by sshiraiwa** [comment]
I agree. It looks to me to address all of them together....

**Comment by sshiraiwa** [comment]
@benzwick 
I am also fixing datacollection. 
vtk.py and datacollection.py is already there. But, at present, it is not loaded when we do import mfem.ser as mfem .
In other word, tthey have to be manually loaded, like this !
```
from  mfem._ser.vtk import VTKFormat_BINARY
from  mfem._ser.datacollection import ParaViewDataCollection

pd = ParaViewDataCollection("Example9", mesh)
pd.SetPrefixPath("ParaView");
pd.RegisterField("solution", u);
pd.SetLevelsOfDetail(order);
pd.SetDataFormat(VTKFormat_BINARY)
pd.SetHighOrderOutput(True)
pd.SetCycle(0)
pd.SetTime(0.0)
pd.Save()
```

Making PR to fix it now...;D

**Comment by sshiraiwa** [comment]
PR (https://github.com/mfem/PyMFEM/pull/75) is made. Please take a look. 
Will be tested and becomes 4.2.0.14, if everything goes well

**Comment by benzwick** [comment]
@sshiraiwa, this is a nice improvement. Yes of course I can review the PR. What is the best way to install that branch (right now I am just using `pip install mfem` to install the stable release)? I tried the following:
```
pip3 install git+https://github.com/mfem/PyMFEM.git@istream_ostream_improvement
```
which installs without errors but when I try to load mfem with `import mfem.ser as mfem` I get the following error:
```
ImportError: libmfem.so.4.2.0: cannot open shared object file: No such file or directory
```

**Comment by benzwick** [comment]
Is it possible to load a compressed grid function that does not end with the `.gz` file extension? I am trying to load the compressed VisIt data collection (`visit_dc.SetCompression(True)`) like this:
```
import mfem.ser as mfem
import numpy as np

def check(a, b, msg):
    assert len(a) == len(b), msg
    assert np.sum(np.abs(a-b)) == 0, msg

def check_mesh(m1, m2, msg):
    assert m1.GetNE() == m2.GetNE(), msg
    assert m1.GetNBE() == m2.GetNBE(), msg
    assert m1.GetNV() == m2.GetNV(), msg

mesh = mfem.Mesh(10, 10, "TRIANGLE")

fec = mfem.H1_FECollection(1, mesh.Dimension())
fespace = mfem.FiniteElementSpace(mesh, fec)

gf = mfem.GridFunction(fespace)
gf.Assign(1.0)
odata = gf.GetDataArray().copy()

# ------------------------------------------------------------------------------
# This works

visit_dc = mfem.VisItDataCollection("test_gf", mesh)
visit_dc.RegisterField("gf", gf)
visit_dc.Save()

mesh2 = mfem.Mesh("test_gf_000000/mesh.000000")
check_mesh(mesh, mesh2, ".mesh2 does not agree with original")

gf2 = mfem.GridFunction(mesh2, "test_gf_000000/gf.000000")
odata2 = gf2.GetDataArray().copy()
check(odata, odata2, "odata2 file does not agree with original")

# ------------------------------------------------------------------------------
# This does not work

visit_dc = mfem.VisItDataCollection("test_gf", mesh)
visit_dc.SetCompression(True)
visit_dc.RegisterField("gf", gf)
visit_dc.Save()

mesh2 = mfem.Mesh("test_gf_000000/mesh.000000")
check_mesh(mesh, mesh2, ".mesh2 does not agree with original")

# This is where the error is:
gf2 = mfem.GridFunction(mesh2, "test_gf_000000/gf.000000")
check(gf, gf2, "gf2 file does not agree with original")
```
This gives the following error:
```
MFEM abort: input stream is not a FiniteElementSpace!
 ... in function: mfem::FiniteElementCollection* mfem::FiniteElementSpace::Load(mfem::Mesh*, std::istream&)
 ... in file: /tmp/pip-req-build-d4latl1v/external/mfem/fem/fespace.cpp:2392

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-6734a2d3d8f3> in <module>
     46 
     47 # This is where the error is:
---> 48 gf2 = mfem.GridFunction(mesh2, "test_gf_000000/gf.000000")
     49 check(gf, gf2, "gf2 file does not agree with original")

~/.local/lib/python3.8/site-packages/mfem/_ser/gridfunc.py in __init__(self, *args)
    529         __init__(GridFunction self, FiniteElementSpace fes, Vector v, int offset) -> GridFunction
    530         """
--> 531         _gridfunc.GridFunction_swiginit(self, _gridfunc.new_GridFunction(*args))
    532 
    533     def SaveToFile(self, gf_file, precision):

RuntimeError: PyMFEM error (mfem::ErrorException): MFEM abort: input stream is not a FiniteElementSpace!
 ... in function: mfem::FiniteElementCollection* mfem::FiniteElementSpace::Load(mfem::Mesh*, std::istream&)
 ... in file: /tmp/pip-req-build-d4latl1v/external/mfem/fem/fespace.cpp:2392
```

Maybe this function could be updated to check whether the file is compressed or not based on the contents of the file:
https://github.com/mfem/PyMFEM/blob/18b7dd9d6ca0662e35020912a8d2c42d2fb02b46/mfem/common/io_stream.hpp#L31-L38

The compressed mesh can be read but not the grid function so maybe there is a clue there as well.

**Comment by sshiraiwa** [comment]
Good point

An issue is that, in MFEM, the constructor receives osgzstream for a compressed
file. So a user has a responsibility to tell the file is .gz. The wrapper, instead, has
to figure out it by itself.

I am not sure what is the best practice here. I could do for example this
test...

https://superuser.com/questions/115902/tell-if-a-gz-file-is-really-gzipped
(By the way, the link in this page does not work…)

Do you have any suggestion?

p.s. I don’t want to change API from C++, such as adding a new member method
for this, since we need to do it for all methods which takes istream & 

—
S

**Comment by benzwick** [comment]
There might be some ideas in the GLVis code but I don't know how that would translate to Python. For example using 
[`ifgzstream`](https://mfem.github.io/doxygen/html/classmfem_1_1ifgzstream.html) or [`named__ifgzstream`](https://mfem.github.io/doxygen/html/classmfem_1_1named__ifgzstream.html) as done here:

https://github.com/GLVis/glvis/blob/95aecd8cf3e3038a36366cef14d5d2986a6a8c1a/glvis.cpp#L1771-L1793

I also agree that the API should be the same as C++.

**Comment by sshiraiwa** [comment]
Not sure what is going on. I did following and odata3 is the same as odata.
```
 import gzip, io
    gf.Print("out_test_gz.dat2.gz")
    with gzip.open("out_test_gz.dat2.gz", 'rt') as f:
       sio = io.StringIO(f.read())    
    gf3 = mfem.GridFunction(fespace)
    gf3.Load(sio, gf.Size())
    odata3 = gf3.GetDataArray().copy()
    check(odata, odata3, ".dat file does not agree with original(gz-io)")  
```

**Comment by benzwick** [comment]
If I use a similar approach for the example I gave above where the data is saved by `VisitDataCollection` by adding the following lines to read the grid function:
```
import gzip, io

with gzip.open("test_gf_000000/gf.000000", 'rt') as f:
   sio = io.StringIO(f.read())

gf3 = mfem.GridFunction(fespace)
gf3.Load(sio, gf.Size())
odata3 = gf3.GetDataArray().copy()
print("odata:  ", odata)
print("odata3: ", odata3)
```
I get the following output:
```
odata:   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]
odata3:  [0.00000000e+000 0.00000000e+000 4.49599738e-321             nan
 1.12646967e-321 0.00000000e+000 1.39804329e-076 1.39803697e-076
 1.39804329e-076 1.39803697e-076 6.22667626e-038 1.03007848e-071
 6.01347002e-154 5.04044187e+223 3.53603683e-057 7.11326544e-067
 1.39804328e-076 1.39642638e-076 1.25713785e-071 9.15604179e-072
 2.58330049e-057 3.11563955e-033 2.00324718e-076 1.26931504e-076
 3.85651486e-057 1.26931241e-076 5.39650260e-062 1.26931701e-076
 5.39650260e-062 1.26931372e-076 1.38080676e-047 1.21090042e-099
 9.72378280e-072 1.21268372e-099 1.38080467e-047 1.21246396e-099
 4.65698279e-033 5.20940318e-090 6.76925701e-043 3.43632253e+179
 1.57731409e-052 3.27802615e+179 1.03357492e-047 3.92068946e+179
 3.67342009e-062 2.95195067e+179 4.64992466e-086 5.05923994e-038
 3.44359475e-086 1.08645955e-071 4.65005967e-086 1.17607308e-047
 3.64468347e-086 2.11101919e-052 4.53910634e-072 8.60394330e-067
 1.56000177e-033 2.31778813e-052 3.63566201e-043 4.17920781e-062
 1.96757658e-062 4.46591228e-033 2.44406612e-154 3.85342527e-057
 1.80608152e-153 5.15250360e-062 1.20824889e-153 7.27133781e-043
 1.73091429e-153 9.95658268e-043 1.31703686e-259 5.94313865e-038
 1.65745938e-076 2.00359504e-076 9.50111420e-043 7.26610339e-043
 1.58660053e-047 4.66535859e-062 7.71094172e-043 3.53665913e-057
 7.25416375e-043 3.05748453e-057 1.79339646e-052 1.17714319e-047
 1.79339644e-052 3.50669707e-033 6.00050344e-067 3.21678888e-057
 5.08074027e-067 1.03052136e-071 7.75258578e-072 3.53665194e-057
 1.26931767e-076 2.73886131e-057 5.08075724e-067 1.31238711e-047
 5.20268398e-090 1.91554784e-076 1.21157101e-099 5.14870130e-062
 1.21156577e-099 1.91554652e-076 5.20842187e-090 1.30506088e-076
 3.75860888e+179 8.54953144e-072 2.95322442e+179 3.66962187e-062
 3.92196565e+179 1.30506098e-076 4.08468681e+179 5.05207761e-086
 4.27631088e-033 3.44360086e-086 5.94199961e-038 5.05221867e-086
 7.48972118e-067 5.05221261e-086 1.69013545e-052 5.54735446e-311
 6.92231189e-310]
```
The values from the file do not seem to be loaded into `gf3`

**Comment by sshiraiwa** [comment]
Understood! For std::istream &, there are methods returning an object, such as Mesh/GridFunction constructor.
Will work on a fix.

**Comment by sshiraiwa** [comment]
@benzwick Please try 4.2.0.16. Let me know if it is fixed.

**Comment by benzwick** [comment]
@sshiraiwa I tried with 4.2.0.16 and it all works now. Thank you very much for fixing this.
