### ISSUE TITLE
Support libCEED

### ISSUE THREAD

**Issue by tzanio** [mfem/PyMFEM#85]
As part of the upgrade to mfem-4.3, can we enable the libCEED support?

**Comment by tzanio** [comment]
ping: @YohannDudouit, @jedbrown

**Comment by sshiraiwa** [comment]
@tzanio  I had an impression that  libCeed is rather backend infrastructure and haven't paid much attention. According to https://github.com/mfem/PyMFEM/blob/master/examples/ex1.py, -pa is already supported. I have a couple of questions...
 1) Is this a matter of adding an option to build MFEM with libCeed on from setup.py or detecting MFEM is compiled with libCeed on?
 2) Is there any low-level API we want to expose to Python?
 3) Which example is good to look?

 Maybe it is worth discussing it off-line.

**Comment by tzanio** [comment]
It is mostly 1, I think but we need to check. Example 1 is a good one to use, we want to be able to run it with `-d ceed`.

**Comment by jedbrown** [comment]
libceed is pip-installable, though the wheel is portable rather than optimized per architecture (and lacks GPU support). For MFEM, you don't actually need the libceed Python package since it's just C++ MFEM calling C libCEED.

We may in the future make libceed.so dynamic in being able to determine at runtime what instructions are supported and choose an appropriate implementation. It would simplify binary distribution, but shouldn't affect the way MFEM uses it.

**Comment by sshiraiwa** [comment]
This is in-progress (https://github.com/mfem/PyMFEM/pull/91)

A quick question, in order to use CEED in MFEM parallel. Do I need to do something special other than adding MFEM_USE_CEED=1?

I am currently using this command options. But somehow, libmfem.so doesn't get linked with libceed.
```
cmake .. -DCMAKE_VERBOSE_MAKEFILE=1
              -DBUILD_SHARED_LIBS=1 
              -DMFEM_ENABLE_EXAMPLES=1 
              -DMFEM_ENABLE_MINIAPPS=1 
              -DCMAKE_SHARED_LINKER_FLAGS=-L/home/shiraiwa/env43/mfem/lib -L/home/shiraiwa/env43/mfem/lib
              -DMFEM_USE_ZLIB=1 
              -DCMAKE_CXX_FLAGS=-std=c++11 
              -DCMAKE_CXX_COMPILER=mpic++ 
              -DMFEM_USE_EXCEPTIONS=0 
              -DCMAKE_INSTALL_PREFIX=/home/shiraiwa/env43/mfem/par 
              -DMFEM_USE_MPI=1 
              -DMFEM_USE_METIS_5=1 
              -DHYPRE_DIR=/home/shiraiwa/env43/mfem 
              -DMETIS_DIR=/home/shiraiwa/env43/mfem 
              -DMFEM_USE_CEED=1 
              -DCEED_DIR=/home/shiraiwa/env43/mfem
```

**Comment by sshiraiwa** [comment]
Closing this since the last question was resolved.
python ex1.py -d ceed-cpu will work with 4.3 release.
