### ISSUE TITLE
Changing viz options for with socketstream

### ISSUE THREAD

**Issue by gillette7** [mfem/PyMFEM#86]
Is there a way to change the visualization options for a glvis call by sending pre-set keyboard commands?  For instance, this works for changing the title of the window:
`title = "Pretty picture"`
`sol_sock.send_text("window_title '" + title)`
I'd like to pass a string of characters indicating how I'd like glvis to do the rendering, akin to the interactive visualization - e.g. `gRc` - but it never seems to work.  Am I getting the syntax wrong here or is this not the right method for doing this?  Thanks.

**Comment by tzanio** [comment]
You can add the keys to the end of the stream as follows:

```python
# Visualization with additional GLVis keys
g = glvis(to_stream(mesh,x) + 'keys ARjlmcbp*******')
g.set_size(600, 400)
g
```

This is done e.g. in https://github.com/GLVis/pyglvis/blob/master/examples/ex1.ipynb.
