### ISSUE TITLE
Getting DOF vertex locations

### ISSUE THREAD

**Issue by jbschroder** [mfem/PyMFEM#90]
Hi All,

Thank you for PyMFEM.  I've really been enjoying it, so far.

I'm currently generating some FEM matrices from example 9, and let's call the matrices that I get "A".

I would also like to get a list of vertex locations for each of A's degrees-of-freedom.  That is, if A is (n x n), I'd like to get an array of size (n x 2) of the x and y locations for each of A's degrees-of-freedom.

I have a hack right now, that seems to mostly work, but only for certain mesh files. 

Is there a recommended way to do this?

Thanks!

Jacob

**Comment by sshiraiwa** [comment]
Do you want to find the coordinate of True DoF (DoF in linear algebra side shown in https://mfem.org/pri-dual-vec/)?

The way I would do is to go to each finite element and check how an integration point is 
transformed to physical space. Take a look at a sample I made (https://github.com/mfem/PyMFEM/blob/mfem-4.3-dev/test/test_dofloc.py). 

I think this works for H1 and DG in serial code. However, I am afraid that this could become non-trivial 
in general. For example, 
-  Answer depends on the element type and also mesh (conforming or non-conforming)
-  With MPI, you may not have the vertex in your local partitioned mesh.

**Comment by jbschroder** [comment]
Hi,

Thank you for the help!  Yes, I am looking for a True DoF to spatial
location map.  I'm also just planning on using Lagrangian bases, so that
should simplify things.  And you're right about parallel -- we just plan on
using serial for now.  So, I think that means that your code snippet should
work well for us.  I just ported it over, and tried for two meshes,
inline-quad.mesh and periodic-hexagon.mesh, and it works great!

We're using the vertices to plot AMG aggregations and coarsenings (as well
as the solution).  The pictures look good.

So, I think you can close the ticket.  Thank you again for the quick help!

Jacob

**Comment by sshiraiwa** [comment]
Closing...Thank you for prompt update.
