### ISSUE TITLE
pymfem with gslib

### ISSUE THREAD

**Issue by junkudo** [mfem/PyMFEM#95]
Hi,
Are there active plans to introduce the gslib `FindPoints` routine in PyMFEM?

**Comment by sshiraiwa** [comment]
@junkudo Thank you for bringing this up.

Our minimum goal is to provide Python version of examples in the level directory (examples/ex[0-9]*). Externals beyond it depends on user's request, and I am happy to take a look at anything.

Just quickly looking into this, adding gslib seems not so complicated.  

Generally speaking, the complexity of supporting an external library depends on 
-  if we can use the feature provided by the external only calling MFEM's access methods. 
-  if the external library can be built as standalone or it ends up introducing further dependencies. 


.

**Comment by junkudo** [comment]
I believe the MFEM's gslib find points satisfies those two requirements.  I could give this a shot if you could point me to where the modifications should be made.

**Comment by sshiraiwa** [comment]
Thank you for volunteering to look into this. Let me put together a small how-to doc. I will 
come back to this after 4.3 wrapper release.
